#!/bin/bash
set -euo pipefail
shopt -s nullglob

DOCS=docs
INCLUDES=$DOCS/_includes
PANDOC_OPTS="-f markdown -t html5 --highlight-style=pygments --wrap=none --email-obfuscation=none"

# Inline SVG used as a PDF icon. Kept as a single line so it drops cleanly
# into generated HTML includes.
PDF_ICON_SVG='<svg class="pdf-icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="9" y1="13" x2="15" y2="13"/><line x1="9" y1="17" x2="15" y2="17"/></svg>'

get_heading() {
    grep -m1 '^#\+ ' "$1" | sed 's/^#\+ //'
}

# Extract the topic line from a remark.js lecture slide deck. The title slide
# is `# CMPE 30: Lecture N` followed by a blank line and then the topic line.
get_slide_topic() {
    awk '/^# CMPE 30: Lecture/{found=1; next} found && /^[A-Za-z`]/{print; exit}' "$1"
}

convert_chapter() {
    local src_dir="$1" md_base="$2" dest="$3" title="$4" parent="$5" nav_order="$6"

    mkdir -p "$(dirname "$dest")"

    local filter_opt=""
    [ -f "$src_dir/callout.lua" ] && filter_opt="--lua-filter=callout.lua"

    {
        printf '%s\n' "---"
        printf 'layout: default\n'
        printf 'title: "%s"\n' "$title"
        printf 'parent: "%s"\n' "$parent"
        printf 'nav_order: %s\n' "$nav_order"
        printf '%s\n\n' "---"
        printf '{%% raw %%}\n'
        (cd "$src_dir" && pandoc "$md_base" $PANDOC_OPTS $filter_opt)
        printf '\n{%% endraw %%}\n'
    } > "$dest"
}

# Run the book's Makefile to build its PDFs. Does not fail the whole site
# build if a book's PDFs can't be built; the pipeline still produces HTML.
build_book_pdfs() {
    local src_dir="$1"
    if [ ! -f "$src_dir/Makefile" ]; then
        return
    fi
    echo "building PDFs in $src_dir"
    # -k: keep going after an error so one bad target (e.g. a chapter with
    # a LaTeX-incompatible Unicode char) doesn't block the other PDFs.
    if ! (cd "$src_dir" && make -k all chapters); then
        echo "warning: one or more PDF targets failed for $src_dir — site will use whatever PDFs were produced" >&2
    fi
}

# Copy a PDF into the docs tree if it exists.
copy_pdf() {
    local src="$1" dst="$2"
    if [ -f "$src" ]; then
        mkdir -p "$(dirname "$dst")"
        cp "$src" "$dst"
    fi
}

# Emit an entry for the chapter list include: chapter title link + optional PDF icon.
emit_chapter_entry() {
    local dest_subdir="$1" base_noext="$2" title="$3" include_pdf="$4"
    printf '  <li>\n'
    printf "    <a href=\"{{ '/%s/%s.html' | relative_url }}\">%s</a>\n" \
        "$dest_subdir" "$base_noext" "$title"
    if [ "$include_pdf" = "yes" ]; then
        printf "    <a class=\"chapter-pdf-link\" href=\"{{ '/%s/%s.pdf' | relative_url }}\" title=\"Download chapter PDF\" aria-label=\"Download %s PDF\">%s</a>\n" \
            "$dest_subdir" "$base_noext" "$title" "$PDF_ICON_SVG"
    fi
    printf '  </li>\n'
}

build_book() {
    local src_dir="$1" dest_subdir="$2" parent="$3" book_slug="$4"

    build_book_pdfs "$src_dir"

    local include_file="$INCLUDES/${dest_subdir}-chapters.html"
    mkdir -p "$INCLUDES" "$DOCS/$dest_subdir"

    # Full book and answer key PDFs get copied next to the chapter PDFs.
    local full_pdf_src="$src_dir/${book_slug}.pdf"
    local full_pdf_dst="$DOCS/$dest_subdir/${dest_subdir}.pdf"
    local answers_pdf_src="$src_dir/${book_slug}-answers.pdf"
    local answers_pdf_dst="$DOCS/$dest_subdir/${dest_subdir}-answers.pdf"
    copy_pdf "$full_pdf_src" "$full_pdf_dst"
    copy_pdf "$answers_pdf_src" "$answers_pdf_dst"

    local has_lectures=no
    [ -d "$src_dir/lectures" ] && has_lectures=yes

    {
        printf '<!-- generated by build-site.sh; do not edit -->\n'

        # Top-of-page book PDF + lectures links.
        if [ -f "$full_pdf_dst" ] || [ -f "$answers_pdf_dst" ] || [ "$has_lectures" = yes ]; then
            printf '<p class="book-pdf-links">\n'
            if [ -f "$full_pdf_dst" ]; then
                printf "  <a class=\"book-pdf-link\" href=\"{{ '/%s/%s.pdf' | relative_url }}\">%s Full book PDF</a>\n" \
                    "$dest_subdir" "$dest_subdir" "$PDF_ICON_SVG"
            fi
            if [ -f "$answers_pdf_dst" ]; then
                printf "  <a class=\"book-pdf-link\" href=\"{{ '/%s/%s-answers.pdf' | relative_url }}\">%s Answer key PDF</a>\n" \
                    "$dest_subdir" "$dest_subdir" "$PDF_ICON_SVG"
            fi
            if [ "$has_lectures" = yes ]; then
                printf "  <a class=\"book-pdf-link\" href=\"{{ '/%s/lectures/' | relative_url }}\">Lectures</a>\n" \
                    "$dest_subdir"
            fi
            printf '</p>\n'
        fi

        printf '<ul class="chapter-list">\n'

        for md in "$src_dir"/ch*.md; do
            local base num title html_dest pdf_src pdf_dst include_pdf
            base=$(basename "$md")
            num=${base%.md}
            num=${num#ch}
            title=$(get_heading "$md")
            html_dest="$DOCS/$dest_subdir/${base%.md}.html"

            convert_chapter "$src_dir" "$base" "$html_dest" "$title" "$parent" "$((10#$num))"

            pdf_src="$src_dir/${base%.md}.pdf"
            pdf_dst="$DOCS/$dest_subdir/${base%.md}.pdf"
            copy_pdf "$pdf_src" "$pdf_dst"
            if [ -f "$pdf_dst" ]; then include_pdf=yes; else include_pdf=no; fi

            emit_chapter_entry "$dest_subdir" "${base%.md}" "$title" "$include_pdf"
        done

        for md in "$src_dir"/app*.md; do
            local base letter order title html_dest pdf_src pdf_dst include_pdf
            base=$(basename "$md")
            letter=${base%.md}
            letter=${letter#app}
            order=$((100 + $(printf '%d' "'$letter") - $(printf '%d' "'A")))
            title=$(get_heading "$md")
            html_dest="$DOCS/$dest_subdir/${base%.md}.html"

            convert_chapter "$src_dir" "$base" "$html_dest" "$title" "$parent" "$order"

            pdf_src="$src_dir/${base%.md}.pdf"
            pdf_dst="$DOCS/$dest_subdir/${base%.md}.pdf"
            copy_pdf "$pdf_src" "$pdf_dst"
            if [ -f "$pdf_dst" ]; then include_pdf=yes; else include_pdf=no; fi

            emit_chapter_entry "$dest_subdir" "${base%.md}" "$title" "$include_pdf"
        done

        printf '</ul>\n'

        for md in "$src_dir"/*-answers.md; do
            local base
            base=$(basename "$md")
            convert_chapter "$src_dir" "$base" \
                "$DOCS/$dest_subdir/answers.html" "Answer Key" "$parent" 200
        done
    } > "$include_file"
}

# Build the lecture slides + notes that ship with a book. Slide decks are
# self-contained remark.js HTML files copied verbatim; lecture notes are
# converted from markdown to Jekyll pages (nav-excluded so they don't clutter
# the sidebar). The lectures index page lists each lecture with links to its
# slides and notes alongside the slide topic line.
build_lectures() {
    local src_dir="$1" dest_subdir="$2" parent="$3"

    [ -d "$src_dir" ] || return 0

    mkdir -p "$DOCS/$dest_subdir"

    # Copy slide decks. Each slide deck lives in src_dir/lectureN/lectureN.html
    # and is self-contained -- no front matter, so Jekyll serves it as a static
    # file.
    local slide_dir lec_name slide_src
    for slide_dir in "$src_dir"/lecture*/; do
        lec_name=$(basename "$slide_dir")
        slide_src="$slide_dir$lec_name.html"
        if [ -f "$slide_src" ]; then
            mkdir -p "$DOCS/$dest_subdir/$lec_name"
            cp "$slide_src" "$DOCS/$dest_subdir/$lec_name/$lec_name.html"
        fi
    done

    # Convert lecture notes markdown to HTML pages. These are nav-excluded so
    # they don't clutter the sidebar; they're reachable from the lectures index.
    local md base notes_title html_dest filter_opt
    filter_opt=""
    [ -f "$src_dir/callout.lua" ] && filter_opt="--lua-filter=callout.lua"
    for md in "$src_dir"/lecture*.md; do
        base=$(basename "$md" .md)
        notes_title=$(get_heading "$md")
        html_dest="$DOCS/$dest_subdir/${base}.html"
        {
            printf '%s\n' "---"
            printf 'layout: default\n'
            printf 'title: "%s"\n' "$notes_title"
            printf 'nav_exclude: true\n'
            printf '%s\n\n' "---"
            printf '{%% raw %%}\n'
            (cd "$src_dir" && pandoc "$base.md" $PANDOC_OPTS $filter_opt)
            printf '\n{%% endraw %%}\n'
        } > "$html_dest"
    done

    # Generate the lectures index page at /<dest_subdir>/.
    local index_dest="$DOCS/$dest_subdir/index.html"
    {
        printf '%s\n' "---"
        printf 'layout: default\n'
        printf 'title: "Lectures"\n'
        printf 'parent: "%s"\n' "$parent"
        printf 'nav_order: 201\n'
        printf '%s\n\n' "---"
        printf '<h1>Lectures</h1>\n'
        printf '<ul class="lecture-list">\n'
        local n slide_html topic notes_url combined cb low high
        for n in $(seq 1 20); do
            slide_html="$src_dir/lecture$n/lecture$n.html"
            [ -f "$slide_html" ] || continue
            topic=$(get_slide_topic "$slide_html")

            # Find the matching notes file: either lectureN.md or lectureX+Y.md
            # where X <= N <= Y.
            notes_url=""
            if [ -f "$src_dir/lecture$n.md" ]; then
                notes_url="lecture$n.html"
            else
                for combined in "$src_dir"/lecture*+*.md; do
                    [ -f "$combined" ] || continue
                    cb=$(basename "$combined" .md)
                    low=${cb#lecture}
                    high=${low#*+}
                    low=${low%+*}
                    if [ "$n" -ge "$low" ] && [ "$n" -le "$high" ]; then
                        notes_url="$cb.html"
                        break
                    fi
                done
            fi

            printf '  <li>\n'
            printf '    <strong>Lecture %d</strong> &mdash; %s\n' "$n" "$topic"
            printf "    [<a href=\"{{ '/%s/lecture%d/lecture%d.html' | relative_url }}\">slides</a>]\n" \
                "$dest_subdir" "$n" "$n"
            if [ -n "$notes_url" ]; then
                printf "    [<a href=\"{{ '/%s/%s' | relative_url }}\">notes</a>]\n" \
                    "$dest_subdir" "$notes_url"
            fi
            printf '  </li>\n'
        done
        printf '</ul>\n'
    } > "$index_dest"
}

build_book sc++  starting-cpp   "Gorgo Starting C++"          "sc++"
build_lectures sc++/lectures starting-cpp/lectures "Gorgo Starting C++"
build_book cc++  continuing-cpp "Gorgo Continuing C++"        "cc++"
build_book c4c++ c-for-cpp      "Gorgo C for C++ Programmers" "c4c++"

# extras
for name in operators numbers; do
    md="$name.md"
    title=$(sed -n 's/^title: *"\(.*\)"/\1/p' "$name/$md")
    [ -z "$title" ] && title=$(get_heading "$name/$md")
    case "$name" in
        operators) order=1 ;;
        *)         order=2 ;;
    esac
    convert_chapter "$name" "$md" "$DOCS/extras/${name}.html" "$title" "Extras" "$order"
done

echo "site built successfully"
